In [1]:
from openbb import obb

if 'info' in obb.reference:
    obj = obb.reference["info"]["extensions"]["openbb_provider_extension"]
    print([item for item in obj if "tdx" in item])

symbols = "601919,600519,000001,00300"
symbols_a = "601919,600519,000001,600325,600028,600036,430047"
symbol_a = "600028"
symbol_hk = "01658"
provider = "tdxquant"
start_date="2025-09-08"
end_date="2025-12-31"

Extensions to add: tdxquant@0.1.5
Extensions to remove: tdxquant@0.1.2

Building...
['tdxquant@0.1.5']

## 1. 股票相关模型 (Equity Models)
### 1.1 Equity Historical Price (股票历史价格)

In [2]:
obb.equity.price.historical(symbol=symbol_a, provider=provider, use_cache=False, start_date=start_date, end_date=end_date).to_dataframe().tail()

TQ数据接口初始化成功，使用路径: C:\Users\roger\src\openbb\tdx\openbb_tdx\utils\helpers.py
TQ数据连接已关闭

,open,high,low,close,volume,amount,change,change_percent
date,,,,,,,,
2026-04-13,5.85,5.86,5.77,5.83,174104992.0,101136.83,0.02,0.344234
2026-04-14,5.80,5.81,5.76,5.78,135035696.0,78000.90,-0.05,-0.857633
2026-04-15,5.76,5.77,5.68,5.69,187819520.0,107187.45,-0.09,-1.557093
2026-04-16,5.67,5.68,5.64,5.66,149625376.0,84635.68,-0.03,-0.527241
2026-04-17,5.67,5.67,5.58,5.58,116432544.0,65294.25,-0.08,-1.413428

### 1.2 Equity Quote (股票实时报价)

In [3]:
obb.equity.price.quote(symbols, provider=provider).to_dataframe().head()

TQ数据接口初始化成功，使用路径: C:\Users\roger\src\openbb\tdx\openbb_tdx\models\equity_quote.py

,symbol,name,exchange,bid,bid_size,ask,ask_size,market_center,last_price,last_size,open,high,low,close,volume,exchange_volume,prev_close,change,change_percent
0,601919,Stock 601919,上海交易所,14.73,433,14.74,353,TdxQuant,14.74,8,14.88,14.91,14.65,14.74,446446,446446,14.92,0.0,0.00
1,600519,Stock 600519,上海交易所,1402.02,2,1402.12,2,TdxQuant,1402.02,10,1400.00,1421.00,1399.87,1402.02,72465,72465,1462.84,-0.1,0.03
2,000001,Stock 000001,深圳交易所,11.05,4305,11.06,865,TdxQuant,11.05,7,11.09,11.11,11.04,11.05,300224,300224,11.09,0.0,0.00
3,00300,Stock 00300,香港交易所,0.00,0,0.00,0,TdxQuant,88.70,100,88.30,89.00,87.70,88.70,1544718,1544718,88.30,0.0,0.11